

<h1> Data Analysis with Python - Lab I </h1>
For more  Data science and Statistics check out <a href= "https://cognitiveclass.ai/courses/data-analysis-python">Data Analysis wit Python</a> for Free! 


<hr>

### Table of Contents 
[**Numpy Library**](#Numpy-Lib)   
[***pandas* Library**](#Pandas-Lib)  
[**CO2 emissions by Country by Year**](#CO2-emissions-by-Country-by-Year)  
[**Get the Data**](#Get-the-Data)  
[**Import the data using *pandas***](#Import-the-data-using-Pandas)  
[**Dataframe characteristics **](#Dataframe-characteristics)  
[**Subsetting the Dataframe**](#Subsetting-the-Dataframe)  
[**Conditional Subsetting**](#Conditional-Subsetting)  





<hr>

<h1>NumPy Library</h1>

__NumPy__: 
- Fast
- Multidimensional Arrays 
- Vectorized Computation

### NumPy ndarray
N-dimensional array object.  
To perform mathematical operations on whole blocks of data. 

In [1]:
# to leverage a library, use "import"
import numpy as np

#### Creating ndarrays
- Use the __array__ function.  
- All of the elements must be the __same type__ (homogeneous)

In [4]:
# create an nd array
data=np.array([[ 1.9526, -0.246 , -0.8856],
[ 0.5639, 0.2379, 0.9104]])

# display the array
data

array([[ 1.9526, -0.246 , -0.8856],
       [ 0.5639,  0.2379,  0.9104]])

Every array has __number of dimensions__ and __shape__ (a tuple indicating the size of each dimension)

In [6]:
# get number of dimensions of array
data.ndim

2

In [7]:
# get size of array
data.shape

(2, 3)

__dtype:__ an object describing the data type of the array:


In [8]:
# get type of data in array

data.dtype

dtype('float64')

In [13]:
dataA=np.array([1,2,3,4])
data.dtype

dtype('float64')

In [15]:
np.__version__

'1.22.1'

__empty__, __range__ , __zeros__ and **ones** arrays

In [20]:
data0 = np.zeros((10,12))
data0.shape

(10, 12)

In [22]:
data1 = np.empty((3, 2))
data1

array([[1.9526, 0.246 ],
       [0.8856, 0.5639],
       [0.2379, 0.9104]])

In [23]:
data2 = np.arange(10)
data2
import matplotlib.pyplot as plt

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.array([1,2,3,4]).reshape(1,-1).shape

(1, 4)

In [ ]:
np.array([1,2,3,4]).reshape(-1,1).shape

### <span style="color: red">YOUR TURN:</span> 
create a 2x4 array of ones and find the data type and shape of the array

In [ ]:
# your code


#### Data Types

In [32]:
data = np.array([1.25, -9.6, 42], dtype=np.string_)
data

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

cast to floating point

In [35]:
data.astype(np.float32)

array([ 1.25, -9.6 , 42.  ], dtype=float32)

### Operations

In [36]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

Arithmetic operations

In [37]:
arr*2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [38]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

### Indexing and Slicing
to select a subset of your data or individual elements

In [55]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Same as Python lists:

In [56]:
arr[5]

5

In [57]:
arr[5:8]

array([5, 6, 7])

you assign a scalar value to a slice:

In [58]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [59]:
arr[5:]

array([12, 12, 12,  8,  9])

In an n-dimensional array, the elements at each index are no longer scalars but rather one-dimensional arrays

In [60]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
arr2d[2]

array([7, 8, 9])

In [62]:
arr2d[0][2]   # also: arr2d[0, 2]

3

In [63]:
arr2d[2:]

array([[7, 8, 9]])

In [64]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [69]:
arr2d[1,0:2]

array([4, 5])

### Boolean Indexing

In [70]:
data=np.random.rand(7, 4)
data

array([[0.94438219, 0.33029629, 0.49360857, 0.09576905],
       [0.67957019, 0.26054875, 0.53171043, 0.48289013],
       [0.05508087, 0.25850789, 0.39380155, 0.70583821],
       [0.11626615, 0.21755182, 0.51504425, 0.36419473],
       [0.57871797, 0.06516491, 0.59365041, 0.40749528],
       [0.45726924, 0.50584562, 0.89243721, 0.21559314],
       [0.70123468, 0.09019319, 0.53951993, 0.69263   ]])

In [71]:
data > 0.4    # Comparison Operators: ==, !=, &, |

array([[ True, False,  True, False],
       [ True, False,  True,  True],
       [False, False, False,  True],
       [False, False,  True, False],
       [ True, False,  True,  True],
       [ True,  True,  True, False],
       [ True, False,  True,  True]])

In [72]:
data[(data > 0.4)]

array([0.94438219, 0.49360857, 0.67957019, 0.53171043, 0.48289013,
       0.70583821, 0.51504425, 0.57871797, 0.59365041, 0.40749528,
       0.45726924, 0.50584562, 0.89243721, 0.70123468, 0.53951993,
       0.69263   ])

### Functions

In [73]:
arr = np.arange(5)
np.sqrt(arr)   # square root function

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [74]:
np.exp(arr)   # exponentiation function

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [75]:
np.mean(arr) # average function

2.0

### <span style="color: red">YOUR TURN:</span> 

Create a 3x2 numpy array (use __ones__ function), and select its second row

In [ ]:
## YOUR CODE BELOW




<h1><em>pandas<em> Library</h1>

*pandas*
- for most kinds of data analysis
- for structured or tabular data
- high-level data structure
- built on top of NumPy  
- time series manipulation


Objects:  
- Series  
- Dataframe  



First, import the *pandas* package

In [76]:
import pandas as pd

#### Series

A Series is a one-dimensional array-like object containing an array of data (of any NumPy data type) and an associated array of data labels, called its index. 

In [77]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [78]:
obj2['b']

7

In [79]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    4
dtype: int64

In [88]:
'b' in obj2

True

In [84]:
'b' in {'b','c','g','c'}

True

### Dataframe
- represents a tabular, spreadsheet-like data structure 
- ceach columns can be a different value type (numeric, string, boolean, etc.)
- has both a row and column index

<h1>CO2 emissions by Country by Year</h1>

Carbon dioxide emissions are those stemming from the burning of fossil fuels and the manufacture of cement. They include carbon dioxide produced during consumption of solid, liquid, and gas fuels and gas flaring.

http://data.worldbank.org/indicator/EN.ATM.CO2E.PC/

<h2>Import the data using Pandas</h2>

#### Import required `pandas` library

In [89]:
import pandas as pd

#### Import data using `pd.read_csv`

In [90]:
data = pd.read_excel("co2_data.xlsx", skiprows = 4)
print('Data read into a pandas dataframe!')

Data read into a pandas dataframe!


In [91]:
type(data) # checks the type of object

pandas.core.frame.DataFrame

In [92]:
data

Country Name Country Code                          Indicator Name  \
0               Aruba          ABW  CO2 emissions (metric tons per capita)   
1             Andorra          AND  CO2 emissions (metric tons per capita)   
2         Afghanistan          AFG  CO2 emissions (metric tons per capita)   
3              Angola          AGO  CO2 emissions (metric tons per capita)   
4             Albania          ALB  CO2 emissions (metric tons per capita)   
..                ...          ...                                     ...   
244       Yemen, Rep.          YEM  CO2 emissions (metric tons per capita)   
245      South Africa          ZAF  CO2 emissions (metric tons per capita)   
246  Congo, Dem. Rep.          COD  CO2 emissions (metric tons per capita)   
247            Zambia          ZMB  CO2 emissions (metric tons per capita)   
248          Zimbabwe          ZWE  CO2 emissions (metric tons per capita)   

     Indicator Code       1990       1995       2000       2005       2010  \
0    EN.ATM.CO2E.PC  29.620165  22.186615  25.547679  24.964531  24.182702   
1    EN.ATM.CO2E.PC        NaN   6.374495   8.018181   7.088128   6.124770   
2    EN.ATM.CO2E.PC   0.221827   0.075646   0.039644   0.054855   0.302936   
3    EN.ATM.CO2E.PC   0.398076   0.844306   0.633625   1.069417   1.401654   
4    EN.ATM.CO2E.PC   2.278387   0.654537   0.978175   1.412498   1.515632   
..              ...        ...        ...        ...        ...        ...   
244  EN.ATM.CO2E.PC   0.802312   0.736948   0.822618   0.977538   1.090060   
245  EN.ATM.CO2E.PC   9.085097   9.035237   8.377512   8.275124   8.957154   
246  EN.ATM.CO2E.PC   0.116420   0.070326   0.034267   0.044326   0.049328   
247  EN.ATM.CO2E.PC   0.300362   0.234599   0.172174   0.189080   0.192079   
248  EN.ATM.CO2E.PC   1.478723   1.295033   1.110956   0.825218   0.646073   

     2015  
0     NaN  
1     NaN  
2     NaN  
3     NaN  
4     NaN  
..    ...  
244   NaN  
245   NaN  
246   NaN  
247   NaN  
248   NaN  

[249 rows x 10 columns]

#### Display first 5 rows of `data` using `head`

In [93]:
data.head()

Country Name Country Code                          Indicator Name  \
0        Aruba          ABW  CO2 emissions (metric tons per capita)   
1      Andorra          AND  CO2 emissions (metric tons per capita)   
2  Afghanistan          AFG  CO2 emissions (metric tons per capita)   
3       Angola          AGO  CO2 emissions (metric tons per capita)   
4      Albania          ALB  CO2 emissions (metric tons per capita)   

   Indicator Code       1990       1995       2000       2005       2010  2015  
0  EN.ATM.CO2E.PC  29.620165  22.186615  25.547679  24.964531  24.182702   NaN  
1  EN.ATM.CO2E.PC        NaN   6.374495   8.018181   7.088128   6.124770   NaN  
2  EN.ATM.CO2E.PC   0.221827   0.075646   0.039644   0.054855   0.302936   NaN  
3  EN.ATM.CO2E.PC   0.398076   0.844306   0.633625   1.069417   1.401654   NaN  
4  EN.ATM.CO2E.PC   2.278387   0.654537   0.978175   1.412498   1.515632   NaN

#### Take just the first two rows using `head`

In [94]:
data.head(2)

Country Name Country Code                          Indicator Name  \
0        Aruba          ABW  CO2 emissions (metric tons per capita)   
1      Andorra          AND  CO2 emissions (metric tons per capita)   

   Indicator Code       1990       1995       2000       2005       2010  2015  
0  EN.ATM.CO2E.PC  29.620165  22.186615  25.547679  24.964531  24.182702   NaN  
1  EN.ATM.CO2E.PC        NaN   6.374495   8.018181   7.088128   6.124770   NaN

In [95]:
data.head(n=1)

Country Name Country Code                          Indicator Name  \
0        Aruba          ABW  CO2 emissions (metric tons per capita)   

   Indicator Code       1990       1995       2000       2005       2010  2015  
0  EN.ATM.CO2E.PC  29.620165  22.186615  25.547679  24.964531  24.182702   NaN

### Don't remember what the parameters are for a function? Use `?`

In [96]:
# to close help window, press q
? data.head

Signature:  data.head(n: 'int' = 5) -> 'FrameOrSeries'
Docstring:
Return the first `n` rows.

This function returns the first `n` rows for the object based
on position. It is useful for quickly testing if your object
has the right type of data in it.

For negative values of `n`, this function returns all rows except
the last `n` rows, equivalent to ``df[:-n]``.

Parameters
----------
n : int, default 5
    Number of rows to select.

Returns
-------
same type as caller
    The first `n` rows of the caller object.

See Also
--------
DataFrame.tail: Returns the last `n` rows.

Examples
--------
>>> df = pd.DataFrame({'animal': ['alligator', 'bee', 'falcon', 'lion',
...                    'monkey', 'parrot', 'shark', 'whale', 'zebra']})
>>> df
      animal
0  alligator
1        bee
2     falcon
3       lion
4     monkey
5     parrot
6      shark
7      whale
8      zebra

Viewing the first 5 lines

>>> df.head()
      animal
0  alligator
1        bee
2     falcon
3       lion
4     monkey


#### Display last 7 rows of data

In [103]:
data.tail()

Country Name Country Code                          Indicator Name  \
244       Yemen, Rep.          YEM  CO2 emissions (metric tons per capita)   
245      South Africa          ZAF  CO2 emissions (metric tons per capita)   
246  Congo, Dem. Rep.          COD  CO2 emissions (metric tons per capita)   
247            Zambia          ZMB  CO2 emissions (metric tons per capita)   
248          Zimbabwe          ZWE  CO2 emissions (metric tons per capita)   

     Indicator Code      1990      1995      2000      2005      2010  2015  
244  EN.ATM.CO2E.PC  0.802312  0.736948  0.822618  0.977538  1.090060   NaN  
245  EN.ATM.CO2E.PC  9.085097  9.035237  8.377512  8.275124  8.957154   NaN  
246  EN.ATM.CO2E.PC  0.116420  0.070326  0.034267  0.044326  0.049328   NaN  
247  EN.ATM.CO2E.PC  0.300362  0.234599  0.172174  0.189080  0.192079   NaN  
248  EN.ATM.CO2E.PC  1.478723  1.295033  1.110956  0.825218  0.646073   NaN

<hr>

<h2>Dataframe characteristics</h2>

#### How many rows and columns are there?

In [104]:
data.shape # (rows, columns)

(249, 10)

In [105]:
data.describe()

1990        1995        2000        2005        2010  2015
count  197.000000  225.000000  227.000000  230.000000  232.000000   0.0
mean     4.314947    4.659084    4.676585    4.864159    4.911618   NaN
std      5.916489    6.650470    6.616818    6.559107    6.100080   NaN
min      0.002900    0.001733    0.021097    0.019411    0.020542   NaN
25%      0.476539    0.604625    0.702071    0.806543    0.797337   NaN
50%      1.627000    2.357140    2.321837    2.674604    2.943880   NaN
75%      6.345085    6.900326    6.638348    7.109675    6.816148   NaN
max     29.620165   61.524218   58.522169   61.989758   42.639076   NaN

#### What are the column names?

In [106]:
data.columns

Index([  'Country Name',   'Country Code', 'Indicator Name', 'Indicator Code',
                   1990,             1995,             2000,             2005,
                   2010,             2015],
      dtype='object')

#### What is the first column name?

In [107]:
data.columns[0]

'Country Name'

#### What is the first and second column name?

In [108]:
data.columns[[0,1]]

Index(['Country Name', 'Country Code'], dtype='object')

<hr>

## Review Questions

### <span style="color: red">YOUR TURN:</span> 

#### Print the first 3 rows of `data`

In [ ]:
## YOUR CODE BELOW



#### Print the names of the first and last column names

In [ ]:
## YOUR CODE BELOW


<hr>

<h2>Subsetting the Dataframe</h2>

### Select columns

#### Select columns by name:

In [109]:
data['Country Name']

0                 Aruba
1               Andorra
2           Afghanistan
3                Angola
4               Albania
             ...       
244         Yemen, Rep.
245        South Africa
246    Congo, Dem. Rep.
247              Zambia
248            Zimbabwe
Name: Country Name, Length: 249, dtype: object

#### Select columns by column number:

In [110]:
data[data.columns[0]]

0                 Aruba
1               Andorra
2           Afghanistan
3                Angola
4               Albania
             ...       
244         Yemen, Rep.
245        South Africa
246    Congo, Dem. Rep.
247              Zambia
248            Zimbabwe
Name: Country Name, Length: 249, dtype: object

#### Select the last column:

In [111]:
data[data.columns[-1]]

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
244   NaN
245   NaN
246   NaN
247   NaN
248   NaN
Name: 2015, Length: 249, dtype: float64

#### Subset Multiple Columns by Name

In [112]:
data[['Country Name', 'Country Code']]

Country Name Country Code
0               Aruba          ABW
1             Andorra          AND
2         Afghanistan          AFG
3              Angola          AGO
4             Albania          ALB
..                ...          ...
244       Yemen, Rep.          YEM
245      South Africa          ZAF
246  Congo, Dem. Rep.          COD
247            Zambia          ZMB
248          Zimbabwe          ZWE

[249 rows x 2 columns]

### Select rows

A few different ways:

In [113]:
data[0:2] # first and second row

Country Name Country Code                          Indicator Name  \
0        Aruba          ABW  CO2 emissions (metric tons per capita)   
1      Andorra          AND  CO2 emissions (metric tons per capita)   

   Indicator Code       1990       1995       2000       2005       2010  2015  
0  EN.ATM.CO2E.PC  29.620165  22.186615  25.547679  24.964531  24.182702   NaN  
1  EN.ATM.CO2E.PC        NaN   6.374495   8.018181   7.088128   6.124770   NaN

In [114]:
data[:2] 

Country Name Country Code                          Indicator Name  \
0        Aruba          ABW  CO2 emissions (metric tons per capita)   
1      Andorra          AND  CO2 emissions (metric tons per capita)   

   Indicator Code       1990       1995       2000       2005       2010  2015  
0  EN.ATM.CO2E.PC  29.620165  22.186615  25.547679  24.964531  24.182702   NaN  
1  EN.ATM.CO2E.PC        NaN   6.374495   8.018181   7.088128   6.124770   NaN

In [117]:
data.iloc[[0,2],2] # first and third rows

0    CO2 emissions (metric tons per capita)
2    CO2 emissions (metric tons per capita)
Name: Indicator Name, dtype: object

In [122]:
data.loc[[0,2],["Country Name",'Indicator Name'] ]

Country Name                          Indicator Name
0        Aruba  CO2 emissions (metric tons per capita)
2  Afghanistan  CO2 emissions (metric tons per capita)

In [123]:
data[0:2]['Country Name']

0      Aruba
1    Andorra
Name: Country Name, dtype: object

In [124]:
#data.ix[0:3, 1:4] # first row

#### Select the last row

In [125]:
data.iloc[-1]

Country Name                                    Zimbabwe
Country Code                                         ZWE
Indicator Name    CO2 emissions (metric tons per capita)
Indicator Code                            EN.ATM.CO2E.PC
1990                                            1.478723
1995                                            1.295033
2000                                            1.110956
2005                                            0.825218
2010                                            0.646073
2015                                                 NaN
Name: 248, dtype: object

<h2, align=center>Conditional Subsetting</h2>

Recall: there are various logical operators to create logical statements.

In [126]:
1 == 2

False

In [127]:
"Me" != "You"

True

In [128]:
1000 > 1

True

When you apply a logical statement to an array, an array of Trues/Falses are returned, with respect to the logical statement.

In [129]:
import numpy as np
my_range = np.array(range(1, 100))
my_range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [130]:
result = my_range > 50
result

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

Then you can use the array of Trues/Falses to return *only the true values* from the original array.

In [131]:
my_range[result]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

#### Select rows based on a condition

In [132]:
data['Country Name']

0                 Aruba
1               Andorra
2           Afghanistan
3                Angola
4               Albania
             ...       
244         Yemen, Rep.
245        South Africa
246    Congo, Dem. Rep.
247              Zambia
248            Zimbabwe
Name: Country Name, Length: 249, dtype: object

In [133]:
# data where the country name is Albania. Returns True/False
data['Country Name'] == 'Albania'

0      False
1      False
2      False
3      False
4       True
       ...  
244    False
245    False
246    False
247    False
248    False
Name: Country Name, Length: 249, dtype: bool

In [143]:
data[data['Country Name'] == 'Canada']

Country Name Country Code                          Indicator Name  \
33       Canada          CAN  CO2 emissions (metric tons per capita)   

    Indicator Code      1990       1995       2000       2005       2010  2015  
33  EN.ATM.CO2E.PC  15.65907  15.927227  17.370452  17.426081  14.589054   NaN

In [134]:
data['Country Name'].head()

0          Aruba
1        Andorra
2    Afghanistan
3         Angola
4        Albania
Name: Country Name, dtype: object

In [137]:
data[data['Country Name'] == 'Albania'] # subset based on condition

Country Name Country Code                          Indicator Name  \
4      Albania          ALB  CO2 emissions (metric tons per capita)   

   Indicator Code      1990      1995      2000      2005      2010  2015  
4  EN.ATM.CO2E.PC  2.278387  0.654537  0.978175  1.412498  1.515632   NaN

#### Select rows based on multiple conditions

In [140]:
data[(data['Country Name'] == 'China') & (data['Country Code'] == 'CHN')]

Country Name Country Code                          Indicator Name  \
38        China          CHN  CO2 emissions (metric tons per capita)   

    Indicator Code      1990      1995      2000      2005      2010  2015  
38  EN.ATM.CO2E.PC  2.167703  2.755755  2.696862  4.441151  6.172489   NaN

In [148]:
data[(data['Country Name'] == 'Canada') & (data['Country Code'] == 'CAN')]

Country Name Country Code                          Indicator Name  \
33       Canada          CAN  CO2 emissions (metric tons per capita)   

    Indicator Code      1990       1995       2000       2005       2010  2015  
33  EN.ATM.CO2E.PC  15.65907  15.927227  17.370452  17.426081  14.589054   NaN

0      False
1      False
2      False
3      False
4      False
       ...  
244    False
245    False
246    False
247    False
248    False
Length: 249, dtype: bool

#### Why does the following return no hits?

In [149]:
data[(data['Country Name'] == 'Canada') & (data['Country Code'] == 'CHN')]

Empty DataFrame
Columns: [Country Name, Country Code, Indicator Name, Indicator Code, 1990, 1995, 2000, 2005, 2010, 2015]
Index: []

### Select data by row and column

What does the following do?

<hr>

## Review Question

### <span style="color: red">YOUR TURN:</span> 
<h3>Find the CO2 Emission per capita for France and Germany in 2010 and 2011</h3>

In [ ]:
# hint
# data['Country Name']== ??
# data[['Country Name', '2010', '2011']].iloc[[??,??]]

In [ ]:
## YOUR CODE BELOW



<hr>
Copyright &copy; 2018 [Cognitive Class](https://cognitiveclass.ai/). This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license/).